
from src.HelperFunctions.InOutHelper import *

# fileName = 'rosalind_revc'
# fIn = open(getFullPathInput(fileName), 'r')
# fOut = open(getFullPathOutput(fileName), 'w')
#s = fIn.readline().strip()
text = 'TTAGTCACCAGACGGACGCAAGTATTATTAGTCACCAGACGGACGATACACTATTAGTCACCAGACGGACGCGTTGCTGTCGTTGCTGTAGACGGACGCAAGTATTACAAGTATTAATACACTACGTTGCTGTTTAGTCACCTTAGTCACCAGACGGACGCGTTGCTGTCGTTGCTGTCGTTGCTGTAGACGGACGCGTTGCTGTTTAGTCACCTTAGTCACCCAAGTATTAATACACTACGTTGCTGTAGACGGACGCGTTGCTGTAGACGGACGCAAGTATTATTAGTCACCATACACTAAGACGGACGAGACGGACGTTAGTCACCCAAGTATTATTAGTCACCTTAGTCACCTTAGTCACCCGTTGCTGTCAAGTATTAAGACGGACGTTAGTCACCATACACTACAAGTATTAATACACTACGTTGCTGTATACACTACGTTGCTGTCGTTGCTGTAGACGGACGCAAGTATTACAAGTATTACGTTGCTGTCAAGTATTATTAGTCACCAGACGGACGTTAGTCACCATACACTAATACACTACGTTGCTGTCAAGTATTAATACACTATTAGTCACCTTAGTCACCTTAGTCACCAGACGGACGATACACTATTAGTCACCTTAGTCACCCGTTGCTGTAGACGGACGTTAGTCACCTTAGTCACCAGACGGACGCAAGTATTAATACACTACGTTGCTGTATACACTACGTTGCTGTAGACGGACGTTAGTCACCAGACGGACGCAAGTATTACAAGTATTATTAGTCACCATACACTAAGACGGACGTTAGTCACCTTAGTCACCTTAGTCACCAGACGGACGTTAGTCACCAGACGGACGCGTTGCTGTCAAGTATTACGTTGCTGTCAAGTATTACGTTGCTGTCAAGTATTACGTTGCTGT'
k = 11

def frequentwords(text, k):
    FP = []
    c = []
    for i in range(0, len(text) - k):
        pattern = text[i:i+k]
        c.append(countwords(text, pattern))
    maxC = max(c)
    for i in range(0, len(text) - k):
        if c[i] == maxC:
            if text[i:i+k] not in FP:
                FP.append(text[i:i+k])
    return FP


def countwords(text, pattern):
    count = 0
    lenPattern = len(pattern)
    for i in range(len(text) - lenPattern+1):
        if text[i:lenPattern+i] == pattern:
            count += 1
    return count

for s in frequentwords(text, k):
    print(s)

# fOut.write(result+'\n')
#
# fIn.close()
# fOut.close()